# -*- coding: utf-8 -*-
"""ExplainabilityAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_xHbsQ6MhCx1W9FVcSt6tHy50YEfYMl
"""

import pandas as pd

"""# Descriptive analysis"""

df = pd.read_csv('HRDataset_v14.csv')

print(f"Dataset shape: {df.shape}")

df.head()

df.dtypes

df.describe()

print(df.isnull().sum())

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values")
plt.show()

"""# Pre-processing"""

# Conversion des colonnes de dates en format datetime
# Cela permet de faire des calculs (âge, ancienneté, etc.)

df["DOB"] = pd.to_datetime(df["DOB"])
df["DateofHire"] = pd.to_datetime(df["DateofHire"])
df["LastPerformanceReview_Date"] = pd.to_datetime(df["LastPerformanceReview_Date"])

# Date actuelle utilisée comme référence
today = pd.to_datetime("today")

# Calcul de l'âge de l'employé
# (différence entre aujourd'hui et la date de naissance)
df["Age"] = (today - df["DOB"]).dt.days // 365

# Calcul de l'ancienneté dans l'entreprise
# (différence entre aujourd'hui et la date d'embauche)
df["Tenure"] = (today - df["DateofHire"]).dt.days // 365

# Liste des colonnes à supprimer
cols_to_drop = [
    "Employee_Name",            # donnée personnelle
    "EmpID",                    # identifiant unique (pas utile pour prédiction)
    "Zip",                      # localisation trop spécifique
    "ManagerName",              # identifiant personnel
    "DOB",                      # remplacé par Age
    "DateofHire",               # remplacé par Tenure
    "DateofTermination",        # contient l'information finale
    "LastPerformanceReview_Date" # date brute, moins utile que dérivées
]

# Suppression des colonnes
df = df.drop(columns=cols_to_drop, errors="ignore")

# Sélection des colonnes contenant du texte
categorical_cols = df.select_dtypes(include=["object"]).columns

# Affichage des colonnes catégorielles
print("Colonnes catégorielles :")
print(categorical_cols)

# Transformation en variables numériques avec One Hot Encoding
# Exemple : Department_IT, Department_Sales, etc.

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Définition de la variable cible
target = "Termd"

# Calcul de la matrice de corrélation
corr = df.corr()

# Corrélation des variables avec la démission
corr_target = corr[target].sort_values(ascending=False)

# Affichage des variables les plus corrélées
print("Variables les plus corrélées avec la démission :")
print(corr_target.head(20))

# Graphique des 15 variables les plus corrélées avec la démission
plt.figure(figsize=(10,8))

corr_target.drop(target).head(15).plot(kind="barh")

plt.title("Top variables corrélées avec la démission")
plt.xlabel("Coefficient de corrélation")
plt.show()

# Visualisation de la matrice de corrélation complète
plt.figure(figsize=(12,10))

sns.heatmap(df.corr(), cmap="coolwarm")

plt.title("Matrice de corrélation")
plt.show()

"""# Prediction

## Random Forest Classifier
"""

# Variables explicatives
X = df.drop("Termd", axis=1)

# Variable cible
y = df["Termd"]



from sklearn.model_selection import train_test_split

# Division du dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,     # 20% pour le test
    random_state=42    # reproductibilité
)

from sklearn.preprocessing import StandardScaler

# Création du scaler
scaler = StandardScaler()

# Normalisation des données d'entraînement
X_train = scaler.fit_transform(X_train)

# Application de la même transformation sur le test
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

# Création du modèle
model = RandomForestClassifier(
    n_estimators=200,   # nombre d'arbres
    random_state=42
)

# Entraînement du modèle
model.fit(X_train, y_train)

# Prédiction sur le dataset de test
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy globale
print("Accuracy :", accuracy_score(y_test, y_pred))

# Rapport détaillé
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(cm, annot=True, fmt="d")

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# Calcul de l'importance des variables
feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

# Affichage des variables les plus importantes
print(feature_importance.head(15))

plt.figure(figsize=(10,6))

feature_importance.head(15).plot(kind="barh")

plt.title("Facteurs les plus influents dans la démission")
plt.xlabel("Importance")

plt.show()

!pip install shap

#utilisation de shap pour faire une ia

import shap
# création de l'objet explainer
explainer = shap.TreeExplainer(model)

# calcul des valeurs SHAP sur les données test
shap_values = explainer.shap_values(X_test)
# graphique global des variables importantes
shap.summary_plot(shap_values[1], X_test, feature_names=X.columns)
# expliquer la prédiction d'un employé
shap.plots.force(
    explainer.expected_value[1],
    shap_values[1][0],
    features=X_test[0],
    feature_names=X.columns
)
shap.plots.waterfall(shap_values[1][0])

